### ISSUE TITLE
The type or namespace name 'WebTool' could not be found

### ISSUE THREAD

**Issue by MarcoLavoro** [GimChuang/UnityWebTool#1]
Hi, i downloaded and opened with unity 2019, i set .net to be on 4.0 or equivalent but i get this error:

Assets\Test\Test_WebTool.cs(8,12): error CS0246: The type or namespace name 'WebTool' could not be found (are you missing a using directive or an assembly reference?)

what i am missing?

**Comment by MarcoLavoro** [comment]
solved, just load the script :D

**Comment by GimChuang** [comment]
Really sorry that I missed your comment! Glad to see you've gotten it to work.
